# Generated by Django 3.2 on 2024-02-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
