# Generated by Django 3.2 on 2024-02-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
