# Generated by Django 3.2 on 2024-03-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscribe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['-id'], 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
