# Generated by Django 3.2 on 2024-03-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('author',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
